#!/usr/bin/env python3
"""Exact reference for the fp8 systolic-array end-to-end test.

Emits expected.h. Arithmetic is Fraction-exact; the array accumulates in C float
(riscv/systolic_array.cc) so an fp8 x fp8 product sum is exact there too.
"""
import random
import struct
import sys
from fractions import Fraction

E4M3, E5M2 = 1, 2


def f8_decode(b, fmt):
    """Decode one fp8 byte. None for NaN/Inf encodings."""
    s = -1 if (b >> 7) else 1
    if fmt == E4M3:
        e, m, ebits, mbits, bias = (b >> 3) & 0xF, b & 0x7, 4, 3, 7
        if e == 0xF and m == 0x7:
            return None
    else:
        e, m, ebits, mbits, bias = (b >> 2) & 0x1F, b & 0x3, 5, 2, 15
        if e == 0x1F:
            return None
    if e == 0:
        return s * Fraction(m, 1 << mbits) * Fraction(1, 1 << (bias - 1))
    return s * (1 + Fraction(m, 1 << mbits)) * Fraction(2) ** (e - bias)


def f8_table(fmt):
    return [(b, f8_decode(b, fmt)) for b in range(256) if f8_decode(b, fmt) is not None]


def f8_encode(x, fmt):
    """Round-to-nearest-even encode, by exhaustive search over the finite codes."""
    x = Fraction(x)
    if x == 0:
        return 0x00
    best = None
    for b, v in f8_table(fmt):
        d = abs(v - x)
        if best is None or d < best[0] or (d == best[0] and (b & 1) < (best[1] & 1)):
            best = (d, b)
    lim = max(v for _, v in f8_table(fmt))
    assert abs(x) <= lim, f"{x} overflows fp8 fmt {fmt}"
    return best[1]


def matmul(W, X, M, K, R, fmt):
    """Y[i][j] = sum_k X[i][k] * W[j][k] -- the array's own indexing."""
    dw = [[f8_decode(W[j * K + k], fmt) for k in range(K)] for j in range(M)]
    dx = [[f8_decode(X[i * K + k], fmt) for k in range(K)] for i in range(R)]
    return [[sum(dx[i][k] * dw[j][k] for k in range(K)) for j in range(M)]
            for i in range(R)]


def f32_bits(y):
    f = float(y)
    assert Fraction(f) == y, f"{y} is not exact in fp32"
    return struct.unpack('<I', struct.pack('<f', f))[0]


CASES = []


def add_case(name, M, K, R, fmt, out_bits, W, X, nvu):
    Y = matmul(W, X, M, K, R, fmt)
    flat = [Y[i][j] for i in range(R) for j in range(M)]
    exp8 = [f8_encode(v, fmt) for v in flat] if out_bits == 8 else []
    exp32 = [f32_bits(v) for v in flat] if out_bits == 32 else []
    CASES.append(dict(name=name, M=M, K=K, R=R, fmt=fmt, out=out_bits, nvu=nvu,
                      W=W, X=X, exp8=exp8, exp32=exp32,
                      human=[str(v) for v in flat]))


# --- small 2x2: values whose product sum can be stated by hand ---------------
# W rows (lane j) = [1,2] and [3,0.5]; X rows = [2,4] and [-1,1].
SW = [0x38, 0x40, 0x44, 0x30]
SX = [0x40, 0x48, 0xB8, 0x38]
SXP = [0x48, 0x48, 0xB8, 0x38]          # X[0][0] 2.0 -> 4.0, the perturbation

add_case("small_e4m3_fp8", 2, 2, 2, E4M3, 8, SW, SX, 4)
add_case("small_e5m2_fp8", 2, 2, 2, E5M2, 8, SW, SX, 4)
add_case("small_e4m3_fp32", 2, 2, 2, E4M3, 32, SW, SX, 4)
add_case("small_e5m2_fp32", 2, 2, 2, E5M2, 32, SW, SX, 4)
add_case("perturb_e4m3_fp8", 2, 2, 2, E4M3, 8, SW, SXP, 4)

# 256+1+1+1 = 259 is exact in fp32 but not in fp8 (step 16 at 256) nor bf16:
# reading 259 back proves the array really accumulates in C float.
add_case("acc_exact_fp32", 1, 4, 1, E4M3, 32,
         [0x78, 0x38, 0x38, 0x38], [0x38, 0x38, 0x38, 0x38], 4)

# --- 32x32x32: every lane of a 32-lane array carries a distinct row ----------
rng = random.Random(20260730)
POOL = [0x00, 0x30, 0xB0, 0x38, 0xB8, 0x3C, 0xBC, 0x40, 0xC0]   # 0,+-.5,1,1.5,2
BW = [rng.choice(POOL) for _ in range(32 * 32)]
BX = [rng.choice(POOL) for _ in range(32 * 32)]

add_case("big_e4m3_fp32", 32, 32, 32, E4M3, 32, BW, BX, 32)
add_case("big_e4m3_fp8", 32, 32, 32, E4M3, 8, BW, BX, 32)
add_case("big_e5m2_fp32", 32, 32, 32, E5M2, 32, BW, BX, 32)


def carr(name, vals, fmt="0x%02x"):
    body = ", ".join(fmt % v for v in vals)
    return f"static const uint{8 if fmt=='0x%02x' else 32}_t {name}[] = {{{body}}};\n"


def main(path):
    out = ["/* generated by ref.py -- do not edit */\n#ifndef FP8_EXPECTED_H\n"
           "#define FP8_EXPECTED_H\n#include <stdint.h>\n\n"]
    for c in CASES:
        n = c["name"]
        out.append(carr(f"w_{n}", c["W"]))
        out.append(carr(f"x_{n}", c["X"]))
        if c["out"] == 8:
            out.append(carr(f"e8_{n}", c["exp8"]))
        else:
            out.append(carr(f"e32_{n}", c["exp32"], "0x%08x"))
        out.append("\n")
    out.append("typedef struct { const char *name; int M, K, R, fmt, out, nvu;\n"
               "  const uint8_t *W, *X, *e8; const uint32_t *e32; } fp8_case_t;\n\n")
    out.append("static const fp8_case_t fp8_cases[] = {\n")
    for c in CASES:
        n = c["name"]
        e8 = f"e8_{n}" if c["out"] == 8 else "0"
        e32 = f"e32_{n}" if c["out"] == 32 else "0"
        out.append(f'  {{"{n}", {c["M"]}, {c["K"]}, {c["R"]}, {c["fmt"]}, '
                   f'{c["out"]}, {c["nvu"]}, w_{n}, x_{n}, {e8}, {e32}}},\n')
    out.append("};\n#define N_FP8_CASES "
               f"{len(CASES)}\n#endif\n")
    open(path, "w").write("".join(out))
    for c in CASES:
        print(f'{c["name"]}: Y(row-major RxM) = '
              + " ".join(c["human"][:8]) + (" ..." if len(c["human"]) > 8 else ""))


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "expected.h")
